core/urls.py
from django.conf.urls import url
from . import views


app_name = 'core'

urlpatterns = [

    # LISTA DE IMOVEIS
    url(r'^home/$', views.Index.as_view(), name='index'),

    # CRUD CLIENTE
    url(r'clientes/$', views.ListarClienteView.as_view(), name='listacliente'),
    url(r'addcliente/$', views.AdicionaClienteView.as_view(), name='addcliente'),
    url(r'editcliente/(?P<pk>[0-9]+)/$',
        views.EditarClienteView.as_view(), name='editcliente'),
    url(r'deletarliente/(?P<pk>[0-9]+)/$',
        views.DeletarClienteView.as_view(), name='delcliente'),

    # VENDA
    url(r'vendas/$', views.ListaClienteVendaView.as_view(), name='listavenda'),
    url(r'addvenda/$', views.AdicionarVendaView.as_view(), name='addvenda'),
    url(r'checkoutvenda/(?P<pk>[0-9]+)/$',
        views.CheckoutView.as_view(), name='checkout'),
    url(r'delvenda/(?P<pk>[0-9]+)/$',
        views.DeletarVendaView.as_view(), name='delvenda')
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('core.urls')),
    path('', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models/cliente.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class Cliente(models.Model):

    # Dados
    primeiro_nome = models.CharField(
        max_length=20, blank=False, null=False, verbose_name='Primeiro nome')
    segundo_nome = models.CharField(
        max_length=20, blank=False, null=False, verbose_name='Segundo nome')
    cpf = models.CharField(unique=True, max_length=13,
                           blank=False, null=False, verbose_name='CPF')
    email = models.EmailField(unique=True, blank=False,
                              null=False, verbose_name='E-mail')
    telefone = models.CharField(
        max_length=15, null=True, blank=True, verbose_name='Telefone')
    quantidade_compras = models.IntegerField(default=0)
    foto = models.ImageField(upload_to='imagens/%Y/%m/%d/', blank=True, null=True)

    # Sobre o objeto
    data_cadastro = models.DateTimeField(editable=False)
    data_edicao = models.DateTimeField()
    criado_por = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=False, blank=True)

    def save(self, *args, **kwargs):

        # Atualizar datas criacao edicao
        if not self.data_cadastro:
            self.data_cadastro = timezone.now()
        self.data_edicao = timezone.now()
        return super(Cliente, self).save(*args, **kwargs)

    def __str__(self):
        return self.email

core/forms/Cliente.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from core.models import Cliente


class ClienteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ClienteForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Cliente
        exclude = ('data_edicao', 'data_cadastro', 'criado_por','quantidade_compras',)
        widgets = {
            'primeiro_nome': forms.TextInput(attrs={'class': 'form-control'}),
            'segundo_nome': forms.TextInput(attrs={'class': 'form-control'}),
            'cpf': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control'}),
            'foto': forms.FileInput(),
        }

        labels = {
            'primeiro_nome': _('Primeiro nome'),
            'segundo_nome': _('Segundo nome'),
            'cpf': _('CPF'),
            'email': _('E-mail'),
            'telefone': _('Telefone/wpp'),
            'foto': _('Foto'),
        }

    def clean(self):
        email = self.cleaned_data.get('email')
        cpf = self.cleaned_data.get('cpf')

        if Cliente.objects.exclude(pk=self.instance.pk).filter(cpf=cpf).exists():
            self.add_error('cpf', ' Já existe um perfil vinculado a esse cpf')
        if Cliente.objects.exclude(pk=self.instance.pk).filter(email=email).exists():
            self.add_error(
                'email', 'Já existe um perfil vinculado a esse email')
        return self.cleaned_data

    def save(self, commit=True):
        instance = super(ClienteForm, self).save(commit=False)
        instance.criado_por = self.request.user
        if commit:
            instance.save()
        return instance

core/views/cliente.py
from django.shortcuts import redirect
from django.urls.base import reverse_lazy
from django.views.generic import DeleteView, CreateView, ListView, UpdateView
from django.contrib import messages

from core.models.venda import Venda
from core.forms.Cliente import ClienteForm
from core.models import Imovel, Cliente


# Classe responsável por renderizar a tela de home
# mostrando somente os imaveis qua estão disponiveis
class Index(ListView):

    template_name = "base/index.html"
    context_object_name = 'all_imoveis'

    def get_queryset(self):
        queryset = Imovel.objects.filter(vendido_status=False)
        return queryset


class AdicionaClienteView(CreateView):

    template_name = "cliente/criar_cliente.html"
    success_url = reverse_lazy('core:listacliente')
    success_message = "Cliente <b>%(descricao)s </b> adicionado com sucesso."

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, descricao=str(self.object))

    def form_valid(self, form):
        messages.success(
            self.request, self.get_success_message(form.cleaned_data))
        return redirect(self.get_success_url())

    def get(self, request, *args, **kwargs):
        self.object = None

        cliente_form = ClienteForm(prefix='cliente_form')

        return self.render_to_response(self.get_context_data(form=cliente_form))

    def post(self, request, *args, **kwargs):
        self.object = None

        cliente_form = ClienteForm(
            request.POST, request.FILES, prefix='cliente_form', request=request)

        if cliente_form.is_valid():
            self.object = cliente_form.save(commit=False)
            self.object.save()

            return self.form_valid(cliente_form)

        return self.form_invalid(form=cliente_form)


class ListarClienteView(ListView):

    template_name = 'cliente/cliente_list.html'
    context_object_name = 'all_clientes'

    def get_queryset(self):
        queryset = Cliente.objects.filter(criado_por=self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ListarClienteView, self).get_context_data(**kwargs)
        context['add_url'] = reverse_lazy('core:addcliente')
        return context


class EditarClienteView(UpdateView):

    template_name = 'cliente/cliente_edit.html'
    success_url = reverse_lazy('core:listacliente')
    context_object_name = 'cliente'
    success_message = "Dados do cliente <b>%(descricao)s </b> editados com sucesso."

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, descricao=str(self.object))

    def form_valid(self, form):
        messages.success(
            self.request, self.get_success_message(form.cleaned_data))
        return redirect(self.get_success_url())

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        obj = Cliente.objects.get(pk=pk)
        return obj

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        cliente_form = ClienteForm(instance=self.object, prefix='cliente_form')

        return self.render_to_response(self.get_context_data(form=cliente_form))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        cliente_form = ClienteForm(
            request.POST, request.FILES, instance=self.object, prefix='cliente_form', request=request)

        if cliente_form.is_valid():
            self.object = cliente_form.save(commit=False)
            self.object.save()

            return self.form_valid(cliente_form)
        return self.form_invalid(form=cliente_form)


class DeletarClienteView(DeleteView):

    template_name = 'cliente/cliente_confirm_delete.html'
    model = Cliente
    success_url = reverse_lazy('core:listacliente')

    def get_queryset(self):
        x = self.kwargs.get(self.pk_url_kwarg)
        queryset = Cliente.objects.all()
        return queryset

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        teste = Venda.objects.filter(cliente_cliente=self.object)

        if teste:
            return redirect('core:listacliente')

        return self.render_to_response(context)

templates/cliente/cliente_confirm_delete.html
{% extends 'base/base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Tem certeza que deseja deletar o cliente "{{ object }}"?</p>
    <button type="submit" class="btn btn-danger">Confirmar</button>
    <button type="button" class="btn btn-warning">
        <a href="{% url 'core:listacliente' %}">Cancelar</a>
    </button>
</form>
{% endblock %}

templates/cliente/cliente_edit.html
{%extends 'base/base.html'%}
{% load static %}
{%block title%}Editar cliente{%endblock%}
{%block content%}

<style>
    .account-settings .user-profile {
        margin: 0 0 1rem 0;
        padding-bottom: 1rem;
        text-align: center;
    }

    .account-settings .user-profile .user-avatar {
        margin: 0 0 1rem 0;
    }

    .account-settings .user-profile .user-avatar img {
        width: 90px;
        height: 90px;
        -webkit-border-radius: 100px;
        -moz-border-radius: 100px;
        border-radius: 100px;
    }

    .account-settings .user-profile h5.user-name {
        margin: 0 0 0.5rem 0;
    }

    .account-settings .user-profile h6.user-email {
        margin: 0;
        font-size: 0.8rem;
        font-weight: 400;
        color: #9fa8b9;
    }

    .account-settings .about {
        margin: 2rem 0 0 0;
        text-align: center;
    }

    .account-settings .about h5 {
        margin: 0 0 15px 0;
        color: #007ae1;
    }

    .account-settings .about p {
        font-size: 0.825rem;
    }

    .form-control {
        border: 1px solid #cfd1d8;
        -webkit-border-radius: 2px;
        -moz-border-radius: 2px;
        border-radius: 2px;
        font-size: .825rem;
        background: #ffffff;
        color: #2e323c;
    }

    .card {
        background: #ffffff;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        border: 0;
        margin-bottom: 1rem;
    }
</style>

<div class="container">
    <div class="row gutters">
        <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
            <div class="card h-100">
                <div class="card-body">
                    <div class="account-settings">
                        <div class="user-profile">
                            <div class="user-avatar">
                                {% if cliente.foto %}
                                <img src="{{ cliente.foto.url }}">
                                {% else %}
                                <img src="{% static 'media/imagens/avatar7.png' %}">
                                {% endif %}
                            </div>
                            <h5 class="user-name">{{cliente.primeiro_nome}} {{cliente.segundo_nome}}</h5>
                            <h6 class="user-email">{{cliente.email}}</h6>
                        </div>
                        <div class="about">
                            <h5>Sobre</h5>
                            <p>Cliente desde {{cliente.data_cadastro|date}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
            <form role="form" method="POST" enctype="multipart/form-data" action="">
                {% include 'base/form_erro_msg.html' %}
                {% csrf_token %}
                <div class="card h-100">
                    <div class="card-body">
                        <div class="row gutters">
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                <h6 class="mb-2 text-primary">Informações pessoais</h6>
                            </div>
                            {% for field in form %}
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <label>{{field.label}}</label>
                                    {{field}}
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-primary my-4">Atualizar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{%endblock%}

templates/cliente/cliente_list.html
{%extends 'base/base.html'%}

{%block title%}Seus Clientes{%endblock%}
{%block content%}

<div class="container">
  {% include 'base/msg_sucesso.html' %}
  {% include 'base/form_error_alert.html' %}
</div>

<section class="container">
  <div class="header-btn my-2">
    <a href="{{add_url}}" class="btn btn-success"><span>Novo cliente</span></a>
    <button class="btn btn-red btn-remove"></button>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Cliente</th>
        <th scope="col">Contatos</th>
        <th scope="col">Telefone</th>
        <th scope="col">Data de cadastro</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for cliente in all_clientes %}
      <tr>
        <td>{{cliente.cliente_cliente.primeiro_nome}} {{cliente.cliente_cliente.segundo_nome}}</td>
        <td>{{cliente.cliente_cliente.email}}</td>
        <td>{{cliente.cliente_cliente.telefone}}</td>
        <td>{{cliente.cliente_cliente.data_cadastro|date}}</td>
        <td>
          <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
            <div class="btn-group" role="group">
              <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle"
                data-bs-toggle="dropdown" aria-expanded="false">
                ...
              </button>
              <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <li><a class="dropdown-item" href="{% url 'core:editcliente' cliente.cliente_cliente.id %}">Editar</a></li>
                <li><a class="dropdown-item" href="{% url 'core:delcliente' cliente.cliente_cliente.id %}">Excluir</a></li>
              </ul>
            </div>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</section>
{%endblock%}

templates/cliente/criar_cliente.html
{%extends 'base/base.html'%}
{%block title%}Criar Cliente{%endblock%}
{%block content%}

{% include 'base/form_erro_msg.html' %}

<div class="row">
    <div class="form-holder">
        <div class="form-content">
            <div class="form-items">
                <h3>Novo cliente</h3>
                <p>Aqu você cadastra um novo cliente.</p>
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="col-md-12">
                        {{field.label}}
                        {{field}}
                    </div>

                    {% endfor %}

                    <div class="form-button mt-3">
                        <button id="submit" type="submit" class="btn btn-primary">Register</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<style>
    .form-holder {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        text-align: center;
    }

    .form-content .form-items {
        padding: 40px;
        display: inline-block;
        width: 100%;
        min-width: 540px;
        -webkit-border-radius: 10px;
        -moz-border-radius: 10px;
        border-radius: 10px;
        text-align: left;
        -webkit-transition: all 0.4s ease;
        transition: all 0.4s ease;
    }

    .form-content h3 {
        text-align: left;
        font-size: 28px;
        font-weight: 600;
        margin-bottom: 5px;
    }

    .form-content h3.form-title {
        margin-bottom: 30px;
    }

    .form-content p {
        text-align: left;
        font-size: 17px;
        font-weight: 300;
        line-height: 20px;
        margin-bottom: 30px;
    }


    .form-content select {
        width: 100%;
        padding: 9px 20px;
        text-align: left;
        border: 0;
        outline: 0;
        border-radius: 6px;
        font-size: 15px;
        font-weight: 300;
        -webkit-transition: all 0.3s ease;
        transition: all 0.3s ease;
        margin-top: 16px;
    }
</style>


{%endblock%}