core/urls.py
from django.conf.urls import url
from . import views


app_name = 'core'

urlpatterns = [

    # LISTA DE IMOVEIS
    url(r'^home/$', views.Index.as_view(), name='index'),

    # CRUD CLIENTE
    url(r'clientes/$', views.ListarClienteView.as_view(), name='listacliente'),
    url(r'addcliente/$', views.AdicionaClienteView.as_view(), name='addcliente'),
    url(r'editcliente/(?P<pk>[0-9]+)/$',
        views.EditarClienteView.as_view(), name='editcliente'),
    url(r'deletarliente/(?P<pk>[0-9]+)/$',
        views.DeletarClienteView.as_view(), name='delcliente'),

    # VENDA
    url(r'vendas/$', views.ListaClienteVendaView.as_view(), name='listavenda'),
    url(r'addvenda/$', views.AdicionarVendaView.as_view(), name='addvenda'),
    url(r'checkoutvenda/(?P<pk>[0-9]+)/$',
        views.CheckoutView.as_view(), name='checkout'),
    url(r'delvenda/(?P<pk>[0-9]+)/$',
        views.DeletarVendaView.as_view(), name='delvenda')
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('core.urls')),
    path('', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from . import views


app_name = 'login'

urlpatterns = [
    url(r'^$', views.UserFormView.as_view(), name='loginview'),
    # logout
    url(r'^logout/$', views.UserLogoutView.as_view(), name='logoutview'),
    # login/criarperfil/
    url(r'^criarperfil/$', views.CriarPefilView.as_view(), name='criarperfilview'),
]

templates/base/base.html
<!doctype html>
<html lang="pt-br">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

  <title>{% block title %}{% endblock %}</title>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'core:index' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:listacliente' %}">Seus clientes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:listavenda' %}">Suas vendas</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            Perfil
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a class="dropdown-item" href="">Seu perfil</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{% url 'login:logoutview' %}">Sair</a></li>
        </ul>
    </li>
    </ul>
  </div>
</nav>

<body>
  {% block content %}

  {% endblock %}

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
    crossorigin="anonymous"></script>


  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/base/form_erro_msg.html
<br/>
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<label class="error-msg"><strong>{{error}}</strong></label>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<label class="error-msg"><strong>{{error}}</strong></label>
{% endfor %}
{% endif %}

templates/base/form_error_alert.html
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger alert-dismissible" role="alert">
  <label>{{field.label}}:</label>
  {{ error|escape }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger alert-dismissible" role="alert">
  {{ error|escape }}
</div>
{% endfor %}
{% endif %}

templates/base/index.html
{% extends 'base/base.html' %}
{%block title%}Home{%endblock%}
{% block content %}

<section class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Endereço</th>
                <th scope="col">Numero</th>
                <th scope="col">Bairro</th>
                <th scope="col">Complemento</th>
                <th scope="col">Cidade</th>
                <th scope="col">Estado</th>
                <th scope="col">CEP</th>
                <th scope="col">Valor</th>
            </tr>
        </thead>
        <tbody>
            {% for campo in all_imoveis %}
            <tr>
                <td>{{campo.endereco}}</td>
                <td>{{campo.numero}}</td>
                <td>{{campo.bairro}}</td>
                <td>{{campo.complemento}}</td>
                <td>{{campo.cidade}}</td>
                <td>{{campo.estado}}</td>
                <td>{{campo.cep}}</td>
                <td>R$ {{campo.valor}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
{% endblock content %}

templates/base/msg_sucesso.html
{%if messages %}
{%for message in messages%}
{% if 'success' in message.tags %}
<div class="alert alert-success alert-dismissible" role="alert">
  {{message|safe}}
</div>
{%endif%}
{%endfor%}
{%endif%}

templates/base/simulacao.html
<div>
    <!-- The Modal -->
    <div class="modal fade" id="contactModal" role="dialog">
        <form method="POST" id="contact-form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Contact Form</h4>
                        <button type="button" class="close " data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        {{ form }}
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="submit" id="contactSubmit" class="btn btn-outline-success">Send</button>
                        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>