core/urls.py
from django.conf.urls import url
from . import views


app_name = 'core'

urlpatterns = [

    # LISTA DE IMOVEIS
    url(r'^home/$', views.Index.as_view(), name='index'),

    # CRUD CLIENTE
    url(r'clientes/$', views.ListarClienteView.as_view(), name='listacliente'),
    url(r'addcliente/$', views.AdicionaClienteView.as_view(), name='addcliente'),
    url(r'editcliente/(?P<pk>[0-9]+)/$',
        views.EditarClienteView.as_view(), name='editcliente'),
    url(r'deletarliente/(?P<pk>[0-9]+)/$',
        views.DeletarClienteView.as_view(), name='delcliente'),

    # VENDA
    url(r'vendas/$', views.ListaClienteVendaView.as_view(), name='listavenda'),
    url(r'addvenda/$', views.AdicionarVendaView.as_view(), name='addvenda'),
    url(r'checkoutvenda/(?P<pk>[0-9]+)/$',
        views.CheckoutView.as_view(), name='checkout'),
    url(r'delvenda/(?P<pk>[0-9]+)/$',
        views.DeletarVendaView.as_view(), name='delvenda')
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('core.urls')),
    path('', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models/venda.py
from django.db import models
from users.models import User
from core.models.cliente import Cliente
from core.models.imovel import Imovel


FORMA_PAGAMENTO = (
    ("parcelado", "Parcelado em 180"),
    ("avista", " À vista")
)


class Venda(models.Model):

    imovel_imovel = models.OneToOneField(
        Imovel, on_delete=models.SET_NULL, null=True, blank=False, verbose_name='Imóvel', related_name='imovel_vendido')
    valor_imovel = models.DecimalField(
        max_digits=7, decimal_places=2, verbose_name='Valor da venda')
    vendedor_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                                      blank=False, verbose_name='Vendedor', related_name='vendedor_user')
    cliente_cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True,
                                        blank=False, verbose_name='Cliente', related_name='cliente_cliente')
    pagamento = models.CharField(
        max_length=255, choices=FORMA_PAGAMENTO, null=False, blank=False, verbose_name='Forma de pagamento')
    venda_status = models.BooleanField(default=False)

core/forms/venda.py
from django.forms import widgets
from core.models.venda import Venda
from django import forms
from django.utils.translation import ugettext_lazy as _


class VendaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(VendaForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Venda
        exclude = ('vendedor_user', 'valor_imovel', 'venda_status',)
        widgets = {
            'imovel_imovel': forms.Select(attrs={'class': 'form-control mt-3'}),
            'cliente_cliente': forms.Select(attrs={'class': 'form-control mt-3'}),
            'pagamento': forms.Select(attrs={'class': 'form-control mt-3'}),
        }
        labels = {
            'imovel_imovel': _('Imovel'),
            'cliente_cliente': _('Cliente'),
            'pagamento': _('Pagamento'),
        }

    def save(self, commit=True):
        instance = super(VendaForm, self).save(commit=False)
        instance.vendedor_user = self.request.user
        instance.valor_imovel = instance.imovel_imovel.valor
        if commit:
            instance.save()
        return instance

core/views/venda.py
from django.views.generic import DeleteView, CreateView, ListView, UpdateView
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from decimal import Decimal

from core.models import Venda, Cliente
from core.forms import VendaForm


# Função para verificar parametro para filtro
def is_valid_queryparam(param):
    return param != '' and param is not None


# Classe responsável por listar todas as vendas
class ListaClienteVendaView(ListView):

    template_name = "venda/lista_venda.html"
    context_object_name = 'vendas'

    def get_queryset(self):
        queryset = Venda.objects.filter(vendedor_user=self.request.user)
        return queryset

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()

        vendas_finalizadas = request.GET.get('vendas_finalizadas')
        vendas_aguardando = request.GET.get('vendas_aguardando')
        clientes = request.GET.get('clientes')

        # Filtar todas vendas finalizadas
        if is_valid_queryparam(vendas_finalizadas):
            self.object_list = self.object_list.filter(venda_status=True)

        # Filtar todas vendas não finalizadas
        if is_valid_queryparam(vendas_aguardando):
            self.object_list = self.object_list.filter(venda_status=False)

        # Filtar vendas de um específico
        if is_valid_queryparam(clientes) and clientes != 'Todos':
            self.object_list = self.object_list.filter(
                cliente_cliente__email=clientes)

        return self.render_to_response(self.get_context_data())

    def get_context_data(self, **kwargs):
        context = super(ListaClienteVendaView, self).get_context_data(**kwargs)
        context['add_url'] = reverse_lazy('core:addvenda')
        context['todos_clientes'] = Cliente.objects.filter(
            criado_por=self.request.user)
        return context


# Classe responsável por adicionar uma venda no sistema
class AdicionarVendaView(CreateView):

    template_name = "venda/criar_venda.html"
    model = Venda
    success_message = "Venda cadastrada, porém, não finalizada para o cliente <b>%(descricao)s </b>."

    # Função responsável por pegar o id da venda criada e encaminha para o CheckoutView
    def get_success_url(self):
        success_url = reverse('core:checkout', kwargs={
            'pk': self.object.pk,
        })
        return success_url

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, descricao=str(self.object.cliente_cliente))

    def form_valid(self, form):
        messages.success(
            self.request, self.get_success_message(form.cleaned_data))
        return redirect(self.get_success_url())

    def get(self, request, *args, **kwargs):
        self.object = None

        venda_form = VendaForm(prefix='venda_form')

        return self.render_to_response(self.get_context_data(form=venda_form))

    def post(self, request, *args, **kwargs):
        self.object = None

        venda_form = VendaForm(
            request.POST, request.FILES, prefix='venda_form', request=request)

        if venda_form.is_valid():
            self.object = venda_form.save(commit=False)
            self.object.save()
            return self.form_valid(venda_form)

        return self.form_invalid(form=venda_form)


# Classe responsável para conferir e salvar, finalizar ou cancelar a venda
class CheckoutView(UpdateView):

    template_name = 'venda/checkout_venda.html'
    context_object_name = 'all_vendas'
    success_url = reverse_lazy('core:listavenda')
    success_message = "Venda para o cliente <b>%(descricao)s </b> <b>finalizada</b> com sucesso."

    def get_success_message(self):
        return self.success_message % dict(descricao=str(self.object.cliente_cliente.email))

    def form_valid(self):
        messages.success(
            self.request, self.get_success_message())
        return redirect(self.success_url)

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        obj = Venda.objects.select_related("cliente_cliente").select_related(
            "imovel_imovel").select_related("vendedor_user").get(pk=pk)
        return obj

    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        context['valor_dividido'] = round(
            (self.object.imovel_imovel.valor/180), 2)
        context['comissao'] = round(
            ((self.object.imovel_imovel.valor) * Decimal(0.05)), 2)
        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        venda_form = VendaForm(instance=self.object, prefix='venda_form')

        return self.render_to_response(self.get_context_data(form=venda_form))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        obj = self.object

        if obj.venda_status == False:

            obj.venda_status = True
            obj.save()

            obj.imovel_imovel.vendido_status = True
            obj.imovel_imovel.propretario = obj.cliente_cliente
            obj.imovel_imovel.save()

            obj.cliente_cliente.quantidade_compras = obj.cliente_cliente.quantidade_compras + 1
            obj.cliente_cliente.save()

            obj.vendedor_user.quantidade_vendas = obj.vendedor_user.quantidade_vendas + 1
            obj.vendedor_user.save()

        return self.form_valid()


class DeletarVendaView(DeleteView):

    template_name = 'venda/venda_confirm_delete.html'
    model = Venda
    success_url = reverse_lazy('core:listavenda')

templates/venda/checkout_venda.html
{%extends 'base/base.html'%}
{%block title%}Checkout{%endblock%}
{%block content%}
<div class="container">

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4 order-md-2 mb-4">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Pagamento</span>
                </h4>
                <ul class="list-group mb-3">
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            {% if all_vendas.pagamento == 'parcelado' %}
                            <h6 class="my-0">Parcelado</h6>
                            {% else %}
                            <h6 class="my-0">À vista</h6>
                            {% endif %}
                            <small class="text-muted">Sem juros</small>
                        </div>
                        {% if all_vendas.pagamento == 'avista' %}
                        <span class="text-muted"><b>1X </b> {{all_vendas.imovel_imovel.valor}}</span>
                        {% else %}
                        <span class="text-muted"><b>180X </b> {{valor_dividido}}</span>
                        {% endif %}
                    </li>
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Total</span>
                        <strong>R${{all_vendas.imovel_imovel.valor}}</strong>
                    </li>
                </ul>
            </div>
            <div class="col-md-8 order-md-1">
                <h4 class="mb-3">Informações do cliente</h4>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="firstName">Primeiro nome</label>
                        <input type="text" readonly readonly class="form-control" value="{{all_vendas.cliente_cliente.primeiro_nome}}"
                            required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Segundo nome</label>
                        <input type="text" readonly class="form-control" value="{{all_vendas.cliente_cliente.segundo_nome}}"
                            required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="email">Email</label>
                        <input type="email" readonly class="form-control" value="{{all_vendas.cliente_cliente.email}}">
                    </div>

                    <div class="col-md-6 mb-3">
                        <label for="email">Telefone</label>
                        <input type="text" readonly class="form-control" value="{{all_vendas.cliente_cliente.telefone}}">
                    </div>
                </div>
                <h4 class="mb-3">Informações do Imovel</h4>
                <div class="row">
                    <div class="col-md-auto">
                        <label>Endereço</label>
                        <input type="text" readonly class="form-control" value="{{all_vendas.imovel_imovel.endereco}}" required>
                    </div>
                    <div class="col">
                        <label>CEP</label>
                        <input type="text" readonly class="form-control" value="{{all_vendas.imovel_imovel.cep}}" required>
                    </div>
                    <div class="col col-lg-2">
                        <label>Numero</label>
                        <input type="text" readonly class="form-control" value="{{all_vendas.imovel_imovel.numero}}" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-auto">
                        <label>Complemento</label>
                        <input type="text" readonly class="form-control" value="{{all_vendas.imovel_imovel.complemento}}"
                            required>
                    </div>
                    <div class="col">
                        <label>Bairo</label>
                        <input type="text" readonly class="form-control" value="{{all_vendas.imovel_imovel.bairro}}" required>
                    </div>
                    <div class="col col-lg-2">
                        <label>Cidade</label>
                        <input type="text" readonly class="form-control" value="{{all_vendas.imovel_imovel.cidade}}" required>
                    </div>
                    <div class="col col-lg-2">
                        <label>Estado</label>
                        <input type="text" readonly class="form-control" value="{{all_vendas.imovel_imovel.estado}}" required>
                    </div>
                </div>

                <h4 class="mb-3">Informações do vendedor</h4>

                <div class="row">
                    <div class="col-md-auto">
                        <label>Nome</label>
                        <input type="text" readonly class="form-control"
                            value="{{all_vendas.vendedor_user.first_name}} {{all_vendas.vendedor_user.last_name}}"
                            required>
                    </div>
                    <div class="col">
                        <label>E-mail</label>
                        <input type="text" readonly class="form-control" value="{{all_vendas.vendedor_user.email}}" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-auto">
                        <label>Comissão</label>
                        <input type="text" readonly class="form-control" value="R${{comissao}}" required>
                    </div>
                    <div class="col-md-auto">
                        <label>Funcionario desde</label>
                        <input type="text" readonly class="form-control" value="{{all_vendas.vendedor_user.date_joined|date}}"
                            required>
                    </div>
                </div>

                {% if all_vendas.venda_status == False %}
                <div class="my-1 pt-5 text-muted text-center text-small">
                    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                        <a href="{% url 'core:delvenda' all_vendas.id %}">
                            <button type="button" class="btn btn-danger">Cancelar venda</button>
                        </a>
                        <a href="{% url 'core:listavenda' %}">
                            <button type="button" class="btn btn-warning">Salvar venda</button>
                        </a>
                        <button type="submit" class="btn btn-success">Finalizar venda</button>
                    </div>
                </div>
                {% endif %}
                <footer class="my-5 pt-5 text-muted text-center text-small">
                </footer>
            </div>
        </div>
    </form>
</div>
{%endblock%}

templates/venda/criar_venda.html
{%extends 'base/base.html'%}
{%block title%}Criar Venda{%endblock%}
{%block content%}

{% include 'base/form_erro_msg.html' %}

<div class="row">
    <div class="form-holder">
        <div class="form-content">
            <div class="form-items">
                <h3>Nova venda</h3>
                <p>Aqu você cadastra uma nova venda, porém, ela inda não vai ser finalizada.</p>
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="col-md-12">
                        {{field.label}}
                        {{field}}
                    </div>

                    {% endfor %}

                    <div class="form-button mt-3">
                        <button id="submit" type="submit" class="btn btn-primary">Register</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<style>
    .form-holder {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        text-align: center;
    }

    .form-content .form-items {
        padding: 40px;
        display: inline-block;
        width: 100%;
        min-width: 540px;
        -webkit-border-radius: 10px;
        -moz-border-radius: 10px;
        border-radius: 10px;
        text-align: left;
        -webkit-transition: all 0.4s ease;
        transition: all 0.4s ease;
    }

    .form-content h3 {
        text-align: left;
        font-size: 28px;
        font-weight: 600;
        margin-bottom: 5px;
    }

    .form-content h3.form-title {
        margin-bottom: 30px;
    }

    .form-content p {
        text-align: left;
        font-size: 17px;
        font-weight: 300;
        line-height: 20px;
        margin-bottom: 30px;
    }


    .form-content select {
        width: 100%;
        padding: 9px 20px;
        text-align: left;
        border: 0;
        outline: 0;
        border-radius: 6px;
        font-size: 15px;
        font-weight: 300;
        -webkit-transition: all 0.3s ease;
        transition: all 0.3s ease;
        margin-top: 16px;
    }
</style>


{%endblock%}

templates/venda/lista_venda.html
{%extends 'base/base.html'%}

{%block title%}Suas vendas{% endblock %}
{%block content%}

<div class="container">
  {% include 'base/msg_sucesso.html' %}
</div>


<div class="container my-2">
  <div class="header-btn">
    <a href="{{add_url}}" class="btn btn-success"><span>Novo Venda</span></a>
    <button class="btn btn-red btn-remove"></button>
  </div>
</div>


<section class="container">
  <form class="form-inline" method="GET">
    <div class="container">
      <div class="row">
        <div class="col">
          <input type="checkbox" id="allvendas" name="allvendas">
          <label for="allvendas">
            Todas vendas
          </label>
        </div>
        <div class="col">
          <input type="checkbox" id="vendas_finalizadas" name="vendas_finalizadas">
          <label for="vendas_finalizadas">
            Vendas Concluída
          </label>
        </div>
        <div class="col">
          <input type="checkbox" id="vendas_aguardando" name="vendas_aguardando">
          <label for="vendas_aguardando">
            Vendas Não Concluída
          </label>
        </div>
        <div class="col">
          <label for="clientes">Clientes</label>
          <select id="clientes" name="clientes">
            <option selected>Todos</option>
            {% for cliente in todos_clientes %}
            <option value="{{ cliente }}">{{ cliente }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="col">
          <button type="submit" class="btn btn-primary">Search</button>
        </div>
      </div>
    </div>

  </form>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Cliente</th>
        <th scope="col">Contatos</th>
        <th scope="col">Telefone</th>
        <th scope="col">Status da venda</th>
        <th scope="col">Imovel</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for venda in vendas %}
      <tr>
        <td>{{venda.cliente_cliente.primeiro_nome}} {{venda.cliente_cliente.segundo_nome}}</td>
        <td>{{venda.cliente_cliente.email}}</td>
        <td>{{venda.cliente_cliente.telefone}}</td>
        <td>
          {% if venda.venda_status %}
          Concluída
          {% else %}
          Aguardando
          {% endif %}
        </td>
        <td>{{ venda.imovel_imovel }}</td>
        <td>
          <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
            <div class="btn-group" role="group">
              <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle"
                data-bs-toggle="dropdown" aria-expanded="false">
                ...
              </button>
              <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <li><a class="dropdown-item" href="{% url 'core:checkout' venda.id %}">
                    {% if venda.venda_status == True %}Visualizar{% else %} Editar {% endif %}</a></li>
              </ul>
            </div>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</section>


{%endblock%}

templates/venda/venda_confirm_delete.html
{% extends 'base/base.html' %}
{% block content %}
{% if object.venda_status == False %}
<form method="post">
    {% csrf_token %}
    <p>Fazendo isso você apaga do historico essa venda {{object.venda_status }}</p>
    <button type="submit" class="btn btn-danger">Confirmar</button>
    <button type="button" class="btn btn-warning">
        <a href="{% url 'core:listavenda' %}">Cancelar</a>
    </button>
</form>
{% endif %}
{% endblock %}